# Generated by Django 3.0.2 on 2020-01-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='eventId',
        ),
    ]
