# Generated by Django 3.0.2 on 2020-01-16 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_auto_20200117_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 17, 52, 3, 569548, tzinfo=utc)),
        ),
    ]
