# Generated by Django 3.0.2 on 2020-01-16 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0007_auto_20200117_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 18, 2, 38, 507865, tzinfo=utc)),
        ),
    ]
