# Generated by Django 3.0.2 on 2020-01-16 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0008_auto_20200117_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 18, 6, 7, 18791, tzinfo=utc)),
        ),
    ]
